ontologies:
  - examples/example with spaces/sdm-reduced.ttl
  - examples/example with spaces/sd-reduced.ttl
name: modelcatalog
output_dir: outputs

openapi:
  openapi: 3.0.1
  info:
    description: This is an API example for the Software Description Ontology for models [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm). The endpoint uses information of models from hydrology, climate, agriculture and economic domains.
    title: Model Catalog
    version: v1.5.0
  externalDocs:
    description: Model Catalog
    url: https://w3id.org/okn/o/sdm
  servers:
    - url: https://api.models.mint.isi.edu/v1.5.0
    - url: https://dev.api.models.mint.isi.edu/v1.5.0
    - url: http://localhost:8080/v1.5.0

firebase:
  key: "test"

endpoint:
  url: http://endpoint.mint.isi.edu/modelCatalog-1.4.0
  prefix: https://w3id.org/okn/i/masd
  graph_base: http://endpoint.mint.isi.edu/modelCatalog-1.4.0/data/

enable_get_paths: true
enable_post_paths: false
enable_delete_paths: false
enable_put_paths: false

auth:
  provider: firebase
follow_references: true

